name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    name: Build
    runs-on: ${{ matrix.platform }}
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get Short SHA8
      id: vars
      run: |
        echo ::set-output name=sha_short::$(git rev-parse --short=8 ${{ github.sha }})"

    - name: Get dependencies
      run: go get -v -t -d ./...
        
    - name: Build
      run: go build -v .

    - name: Upload Artifacts
      if: matrix.platform != 'windows-latest'
      uses: actions/upload-artifact@v1.0.0
      env:
        SHA8: ${{ steps.vars.outputs.sha_short }}
      with:
        name: boom-bot-${{ matrix.platform }}-$SHA8
        path: boom-bot

    - name: Upload Artifacts
      if: matrix.platform == 'windows-latest'
      uses: actions/upload-artifact@v1.0.0
      env:
        SHA8: ${{ steps.vars.outputs.sha_short }}
      with:
        SHA8: 
        name: boom-bot-${{ matrix.platform }}-$SHA8
        path: boom-bot.exe
